name: cullinarium
description: "Online platform for food lovers"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  auto_route: ^9.2.2
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/
   - assets/fonts/gotham/
   - assets/layout/
   - assets/temp/

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/gotham/gotham_bold.otf
          weight: 700
        - asset: assets/fonts/gotham/gotham_light.otf
          weight: 300
        - asset: assets/fonts/gotham/gotham_medium.otf
          weight: 500
        - asset: assets/fonts/gotham/gotham_book.otf
          weight: 100

