// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslX_XxFh002xN1-iBnMJuz83nuUY7R2c',
    appId: '1:190144091387:web:83756eb263f25dc6becc5e',
    messagingSenderId: '190144091387',
    projectId: 'cullinarium-202ec',
    authDomain: 'cullinarium-202ec.firebaseapp.com',
    storageBucket: 'cullinarium-202ec.firebasestorage.app',
    measurementId: 'G-CDJNFZSX71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhtKN8ho3cYhsWE2Yp9CfbDeaHF48-7gg',
    appId: '1:190144091387:android:aabb109b9a6787aabecc5e',
    messagingSenderId: '190144091387',
    projectId: 'cullinarium-202ec',
    storageBucket: 'cullinarium-202ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOZ15UUmGFcCpeokQEdCp-L6HXV1Y5h9A',
    appId: '1:190144091387:ios:07a5a7790e78b798becc5e',
    messagingSenderId: '190144091387',
    projectId: 'cullinarium-202ec',
    storageBucket: 'cullinarium-202ec.firebasestorage.app',
    iosBundleId: 'com.example.cullinarium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOZ15UUmGFcCpeokQEdCp-L6HXV1Y5h9A',
    appId: '1:190144091387:ios:07a5a7790e78b798becc5e',
    messagingSenderId: '190144091387',
    projectId: 'cullinarium-202ec',
    storageBucket: 'cullinarium-202ec.firebasestorage.app',
    iosBundleId: 'com.example.cullinarium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDslX_XxFh002xN1-iBnMJuz83nuUY7R2c',
    appId: '1:190144091387:web:f058dafecb99863abecc5e',
    messagingSenderId: '190144091387',
    projectId: 'cullinarium-202ec',
    authDomain: 'cullinarium-202ec.firebaseapp.com',
    storageBucket: 'cullinarium-202ec.firebasestorage.app',
    measurementId: 'G-MYHX1MKJGB',
  );

}